/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.speakerphone;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.content.Context;
import android.media.AudioManager;

@Kroll.module(name = "Speakerphone", id = "ti.speakerphone")
public class SpeakerphoneModule extends KrollModule {

	AudioManager am;
	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public SpeakerphoneModule() {
		super();
		am = (AudioManager) TiApplication.getInstance().getApplicationContext().getSystemService(Context.AUDIO_SERVICE);   
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
	}

	// Methods
	@Kroll.method
	public boolean isSpeakerphoneOn() {
		return  am.isSpeakerphoneOn();
	}

	@Kroll.method
	public void setSpeakerphoneOn(boolean on) {
		am.setSpeakerphoneOn(on);
	}

	@Kroll.method
	public void toggleSpeakerphoneOn() {
		am.setSpeakerphoneOn(!am.isSpeakerphoneOn());
	}
	

}
